---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: development
spec:
  selector:
    matchLabels:
      run: postgresql
  template:
    metadata:
      labels:
        run: postgresql
    spec:
      containers:
      - name: postgresql
        image: registry.gitlab.com/ngonzalez121/demo-app-database-org/postgresql
        resources:
          requests:
            memory: "500M"
            cpu: "0.5"
          limits:
            memory: "2G"
            cpu: "2"
        ports:
        - name: postgresql
          containerPort: 5432
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
