---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-env
  namespace: development
  labels:
    app: postgresql
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: B7au!c7ex5@b8mywCdhe#RadwJxSn8Hywd&eRMyj
