---
apiVersion: v1
kind: Service
metadata:
  name: app-backend-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: app-backend
  ports:
  - port: 4000
    name: puma
    targetPort: 4000
