---
apiVersion: v1
kind: Service
metadata:
  name: app-stream-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: app-stream
  ports:
  - port: 5000
    name: puma
    targetPort: 5000
