---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: k8s
spec:
  type: LoadBalancer
  loadBalancerIP: 10.101.10.167
  selector:
    run: debian-sid
  ports:
  - port: 22
    name: ssh
    targetPort: 22
  - port: 80
    name: nginx
    targetPort: 8000
