---
apiVersion: v1
kind: Service
metadata:
  name: app-loadbalancer
  namespace: k8s
spec:
  type: LoadBalancer
  selector:
    run: app-debian-sid
  ports:
  - port: 80
    name: nginx
    targetPort: 8000
