---
apiVersion: v1
kind: Service
metadata:
  name: app-loadbalancer
  namespace: k8s
spec:
  type: LoadBalancer
  selector:
    run: app
  ports:
  - port: 80
    name: frontend-http
    targetPort: 8000
  - port: 443
    name: frontend-https
    targetPort: 9000
  - port: 9090
    name: backend-https
    targetPort: 9090
