---
apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  namespace: k8s
spec:
  type: LoadBalancer
  selector:
    run: backend
  ports:
  - port: 9090
    name: nginx-https
    targetPort: 9090
