---
apiVersion: v1
kind: Service
metadata:
  name: database-loadbalancer
  namespace: k8s
spec:
  type: LoadBalancer
  selector:
    run: database
  ports:
  - port: 5432
    name: postgresql
    targetPort: 5432
  - port: 6379
    name: redis
    targetPort: 6379
