---
apiVersion: v1
kind: Service
metadata:
  name: demonginxstream-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: demonginxstream
  ports:
  - port: 5050
    name: https
    targetPort: 5050
