---
apiVersion: v1
kind: Service
metadata:
  name: demonginxfrontend-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: demonginxfrontend
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
