---
apiVersion: v1
kind: Service
metadata:
  name: demoappstream-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: demoappstream
  ports:
  - port: 5000
    name: puma
    targetPort: 5000
