---
apiVersion: v1
kind: Service
metadata:
  name: demoappbackend-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: demoappbackend
  ports:
  - port: 3000
    name: puma
    targetPort: 3000
