---
apiVersion: v1
kind: Service
metadata:
  name: demopostgresql-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: demopostgresql
  ports:
  - port: 5432
    name: postgresql
    targetPort: 5432