---
apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: k8s
spec:
  type: LoadBalancer
  selector:
    run: frontend
  ports:
  - port: 80
    name: nginx-http
    targetPort: 8000
  - port: 443
    name: nginx-https
    targetPort: 9000
