---
apiVersion: v1
kind: Service
metadata:
  name: nginx-showcase-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: nginx-showcase
  ports:
  - port: 6060
    name: nginx
    targetPort: 6060
  - port: 2224
    name: nginx-status
    targetPort: 2224
