---
apiVersion: v1
kind: Service
metadata:
  name: nginx-stream-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: nginx-stream
  ports:
  - port: 5050
    name: https
    targetPort: 5050
  - port: 2221
    name: nginx-status
    targetPort: 2221
