---
apiVersion: v1
kind: Service
metadata:
  name: nginx-backend-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: nginx-backend
  ports:
  - port: 9090
    name: nginx
    targetPort: 9090
  - port: 2222
    name: nginx-status
    targetPort: 2222
