---
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: nginx-frontend
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  - port: 2220
    name: nginx-status
    targetPort: 2220
