---
apiVersion: v1
kind: Service
metadata:
  name: redis-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    run: redis
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
