---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stream
  namespace: development
spec:
  selector:
    matchLabels:
      run: app-stream
  template:
    metadata:
      labels:
        run: app-stream
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data
      - name: config
        secret:
          secretName: app-stream-env
      containers:
      - name: app-stream
        image: registry.gitlab.com/ngonzalez121/demo-app-stream/app-stream
        ports:
        - name: puma
          containerPort: 5000
          hostPort: 5000
        livenessProbe:
          httpGet:
            path: /_health
            port: 5000
          initialDelaySeconds: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /_health
            port: 5000
          initialDelaySeconds: 3
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /tmp/secrets/
          readOnly: true
        - name: data
          mountPath: /data
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
