---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: development
spec:
  selector:
    matchLabels:
      run: app-backend
  template:
    metadata:
      labels:
        run: app-backend
    spec:
      volumes:
      - name: config
        secret:
          secretName: app-backend-env
      containers:
      - name: app-backend
        image: registry.gitlab.com/ngonzalez121/demo-app-backend-org/app-backend
        resources:
          requests:
            ephemeral-storage: "1G"
            memory: "500M"
            cpu: "0.5"
          limits:
            ephemeral-storage: "2G"
            memory: "2G"
            cpu: "2"
        ports:
        - name: puma
          containerPort: 4000
          hostPort: 4000
        livenessProbe:
          httpGet:
            path: /_health
            port: 4000
          initialDelaySeconds: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /_health
            port: 4000
          initialDelaySeconds: 3
          timeoutSeconds: 1
        volumeMounts:
        - name: ephemeral
          mountPath: /tmp
        - name: config
          mountPath: /etc/secrets/
          readOnly: true
      volumes:
      - name: ephemeral
        emptyDir:
          sizeLimit: "500M"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
