---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: k8s
spec:
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pv-claim
      containers:
      - name: app
        image: ngonzalez121/debian-sid
        ports:
        - name: ssh
          containerPort: 22
        - name: stream-https
          containerPort: 3000
        - name: frontend-http
          containerPort: 8000
        - name: frontend-https
          containerPort: 9000
        - name: backend-https
          containerPort: 9090
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - name: data
          mountPath: /data
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
