---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: hebe
spec:
  selector:
    matchLabels:
      run: debian-sid
  template:
    metadata:
      labels:
        run: debian-sid
    spec:
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      containers:
      - name: debian-sid
        image: gcr.io/hebe-299715/debian-sid
        ports:
        - name: ssh
          containerPort: 22
        - name: nginx
          containerPort: 8000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - name: sys
          mountPath: /sys:ro
