---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: k8s
spec:
  selector:
    matchLabels:
      run: database
  template:
    metadata:
      labels:
        run: database
    spec:
      containers:
      - name: database
        image: ngonzalez121/debian-sid
        ports:
        - name: ssh
          containerPort: 22
        - name: postgresql
          containerPort: 5432
        - name: redis
          containerPort: 6379
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
