---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoappbackend
  namespace: development
spec:
  selector:
    matchLabels:
      run: demoappbackend
  template:
    metadata:
      labels:
        run: demoappbackend
    spec:
      volumes:
      - name: config
        secret:
          secretName: demoappbackend-env
      containers:
      - name: demoappbackend
        image: ngonzalez121/demoappbackend
        ports:
        - name: puma
          containerPort: 3000
          hostPort: 3000
        livenessProbe:
          httpGet:
            path: /_health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /_health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /tmp/secrets/
          readOnly: true
      imagePullSecrets:
      - name: demoappbackend-env
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
