---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonginxstream
  namespace: development
spec:
  selector:
    matchLabels:
      run: demonginxstream
  template:
    metadata:
      labels:
        run: demonginxstream
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data
      containers:
      - name: demonginxstream
        image: ngonzalez121/demonginxstream
        ports:
        - name: https
          containerPort: 5050
          hostPort: 5050
        volumeMounts:
        - name: data
          mountPath: /data
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
