---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: k8s
spec:
  selector:
    matchLabels:
      run: elastic
  template:
    metadata:
      labels:
        run: elastic
    spec:
      containers:
      - name: elastic
        image: ngonzalez121/debian-sid
        ports:
        - name: ssh
          containerPort: 22
        - name: logstash-tcp
          containerPort: 4000
        - name: logstash-beats
          containerPort: 5044
        - name: nginx
          containerPort: 8000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
