---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: k8s
spec:
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: node:latest
        ports:
        - name: ssh
          containerPort: 22
        - name: nginx-http
          containerPort: 8000
        - name: nginx-https
          containerPort: 9000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
