---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: import
  namespace: k8s
spec:
  selector:
    matchLabels:
      run: import
  template:
    metadata:
      labels:
        run: import
    spec:
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: data
        persistentVolumeClaim:
          claimName: pv-claim
      containers:
      - name: import
        image: ngonzalez121/debian-sid
        ports:
        - name: ssh
          containerPort: 22
        - name: nginx-http
          containerPort: 3000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup:ro
        - name: data
          mountPath: /data
