---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: k8s
spec:
  selector:
    matchLabels:
      run: debian-stretch
  template:
    metadata:
      labels:
        run: debian-stretch
    spec:
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      containers:
      - name: debian-stretch
        image: ngonzalez121/debian-stretch
        ports:
        - name: ssh
          containerPort: 22
        - name: logstash-tcp
          containerPort: 4000
        - name: logstash-beats
          containerPort: 5044
        - name: nginx
          containerPort: 8000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup:ro
