---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: development
spec:
  selector:
    matchLabels:
      run: nginx-frontend
  template:
    metadata:
      labels:
        run: nginx-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: ngonzalez121/nginx-frontend
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
