---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend
  namespace: development
spec:
  selector:
    matchLabels:
      run: nginx-backend
  template:
    metadata:
      labels:
        run: nginx-backend
    spec:
      containers:
      - name: nginx-backend
        image: registry.gitlab.com/ngonzalez121/demo-app-backend-org/nginx-backend
        ports:
        - name: nginx
          containerPort: 4040
        - name: nginx-status
          containerPort: 2222
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - appshare.site
        options:
          - name: ndots
            value: "2"
          - name: eth0
