---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: development
spec:
  selector:
    matchLabels:
      run: nginx-frontend
  template:
    metadata:
      labels:
        run: nginx-frontend
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data
      containers:
      - name: nginx-frontend
        image: registry.gitlab.com/ngonzalez121/demo-app-frontend-org/nginx-frontend
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: nginx-status
          containerPort: 2220
        volumeMounts:
        - name: data
          mountPath: /data
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - appshare.site
        options:
          - name: ndots
            value: "2"
          - name: eth0
