---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stream
  namespace: development
spec:
  selector:
    matchLabels:
      run: nginx-stream
  template:
    metadata:
      labels:
        run: nginx-stream
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data
      containers:
      - name: nginx-stream
        image: registry.gitlab.com/ngonzalez121/demo-app-stream-org/nginx-stream
        ports:
        - name: https
          containerPort: 5050
        - name: nginx-status
          containerPort: 2221
        volumeMounts:
        - name: data
          mountPath: /data
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
