deploy/postgresql.yaml ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: development
spec:
  selector:
    matchLabels:
      run: postgresql
  template:
    metadata:
      labels:
        run: postgresql
    spec:
      containers:
      - name: postgresql
        image: ngonzalez121/postgresql
        ports:
        - name: postgresql
          containerPort: 5432
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - link12.ddns.net
        options:
          - name: ndots
            value: "2"
          - name: eth0
