---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: development
  name: pv1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  local:
    path: /data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-1
