---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pv-claim
  namespace: k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: app-pv
  storageClassName: local-storage
