---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-secret
  namespace: development
  labels:
    app: postgresql
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 
